import { Question } from './types';

export const QUESTIONS: Record<string, Question[]> = {
  QUAL_1: [
    { id: 'q1_1', text: "Qual è la capitale dell'Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctAnswer: 2, difficulty: 'facile' },
    { id: 'q1_2', text: "In che anno è caduto il muro di Berlino?", options: ["1987", "1989", "1991", "1993"], correctAnswer: 1, difficulty: 'facile' },
    { id: 'q1_3', text: "Qual è l'elemento chimico con simbolo 'O'?", options: ["Oro", "Osmio", "Ossigeno", "Olio"], correctAnswer: 2, difficulty: 'facile' },
    { id: 'q1_4', text: "Qual è il pianeta più grande del sistema solare?", options: ["Marte", "Saturno", "Giove", "Nettuno"], correctAnswer: 2, difficulty: 'media' },
    { id: 'q1_5', text: "Chi ha scritto 'La Divina Commedia'?", options: ["Petrarca", "Dante Alighieri", "Boccaccio", "Ariosto"], correctAnswer: 1, difficulty: 'media' },
    { id: 'q1_6', text: "Quanti sono i continenti sulla Terra?", options: ["5", "6", "7", "8"], correctAnswer: 1, difficulty: 'media' },
    { id: 'q1_7', text: "Chi dipinse la Gioconda?", options: ["Michelangelo", "Raffaello", "Leonardo da Vinci", "Donatello"], correctAnswer: 2, difficulty: 'difficile' },
    { id: 'q1_8', text: "Qual è la lingua più parlata al mondo?", options: ["Inglese", "Cinese Mandarino", "Spagnolo", "Hindi"], correctAnswer: 1, difficulty: 'difficile' },
    { id: 'q1_9', text: "Qual è il fiume più lungo del mondo?", options: ["Nilo", "Rio delle Amazzoni", "Mississippi", "Danubio"], correctAnswer: 1, difficulty: 'difficile' },
    { id: 'q1_10', text: "Chi è l'autore di '1984'?", options: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "Isaac Asimov"], correctAnswer: 1, difficulty: 'difficile' },
    { id: 'q1_11', text: "Quale paese ha inventato la pizza?", options: ["Grecia", "Italia", "USA", "Egitto"], correctAnswer: 1, difficulty: 'facile' },
    { id: 'q1_12', text: "Quante zampe ha un ragno?", options: ["4", "6", "8", "10"], correctAnswer: 2, difficulty: 'facile' },
    { id: 'q1_13', text: "Qual è il colore del cielo in una giornata serena?", options: ["Verde", "Rosso", "Blu", "Giallo"], correctAnswer: 2, difficulty: 'facile' },
    { id: 'q1_14', text: "Chi ha scoperto l'America?", options: ["Marco Polo", "Amerigo Vespucci", "Cristoforo Colombo", "Vasco da Gama"], correctAnswer: 2, difficulty: 'facile' },
    { id: 'q1_15', text: "Qual è l'animale terrestre più veloce?", options: ["Leone", "Ghepardo", "Cavallo", "Struzzo"], correctAnswer: 1, difficulty: 'facile' },
    { id: 'q1_16', text: "Qual è lo stato più grande del mondo per superficie?", options: ["Canada", "Cina", "USA", "Russia"], correctAnswer: 3, difficulty: 'media' },
    { id: 'q1_17', text: "In quale città si trova la Torre Eiffel?", options: ["Londra", "Berlino", "Parigi", "Madrid"], correctAnswer: 2, difficulty: 'facile' },
    { id: 'q1_18', text: "Qual è la valuta ufficiale del Giappone?", options: ["Won", "Yuan", "Yen", "Dollaro"], correctAnswer: 2, difficulty: 'facile' },
    { id: 'q1_19', text: "Chi ha inventato il telefono?", options: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"], correctAnswer: 1, difficulty: 'media' },
    { id: 'q1_20', text: "Qual è il metallo più leggero?", options: ["Alluminio", "Litio", "Magnesio", "Titanio"], correctAnswer: 1, difficulty: 'difficile' }
  ],
  QUAL_2: [
    { id: 'q2_1', text: "Quale film ha vinto l'Oscar come Miglior Film nel 2020?", options: ["1917", "Joker", "Parasite", "The Irishman"], correctAnswer: 2, difficulty: 'facile' },
    { id: 'q2_2', text: "Chi è il 'Re del Pop'?", options: ["Elvis Presley", "Michael Jackson", "Prince", "Freddie Mercury"], correctAnswer: 1, difficulty: 'facile' },
    { id: 'q2_3', text: "In quale città è ambientato il film 'La Grande Bellezza'?", options: ["Milano", "Napoli", "Roma", "Venezia"], correctAnswer: 2, difficulty: 'facile' },
    { id: 'q2_4', text: "Quale di questi è un romanzo di Alessandro Manzoni?", options: ["Il Fu Mattia Pascal", "I Promessi Sposi", "La Coscienza di Zeno", "Il Gattopardo"], correctAnswer: 1, difficulty: 'media' },
    { id: 'q2_5', text: "Chi canta 'Bohemian Rhapsody'?", options: ["The Beatles", "The Rolling Stones", "Queen", "Led Zeppelin"], correctAnswer: 2, difficulty: 'media' },
    { id: 'q2_6', text: "Quale attore interpreta Iron Man nel Marvel Cinematic Universe?", options: ["Chris Evans", "Chris Hemsworth", "Robert Downey Jr.", "Mark Ruffalo"], correctAnswer: 2, difficulty: 'media' },
    { id: 'q2_7', text: "Quale di queste opere è di William Shakespeare?", options: ["Amleto", "I Miserabili", "Don Chisciotte", "Guerra e Pace"], correctAnswer: 0, difficulty: 'difficile' },
    { id: 'q2_8', text: "Chi è il regista di 'Pulp Fiction'?", options: ["Steven Spielberg", "Martin Scorsese", "Quentin Tarantino", "Christopher Nolan"], correctAnswer: 2, difficulty: 'difficile' },
    { id: 'q2_9', text: "Quale strumento suonava Jimi Hendrix?", options: ["Batteria", "Basso", "Chitarra", "Pianoforte"], correctAnswer: 2, difficulty: 'difficile' },
    { id: 'q2_10', text: "Chi ha scritto 'Harry Potter'?", options: ["J.R.R. Tolkien", "C.S. Lewis", "J.K. Rowling", "Stephen King"], correctAnswer: 2, difficulty: 'difficile' },
    { id: 'q2_11', text: "Chi ha dipinto 'La persistenza della memoria'?", options: ["Picasso", "Dalì", "Van Gogh", "Magritte"], correctAnswer: 1, difficulty: 'difficile' },
    { id: 'q2_12', text: "Quale gruppo musicale ha pubblicato 'The Dark Side of the Moon'?", options: ["The Who", "Pink Floyd", "Genesis", "Yes"], correctAnswer: 1, difficulty: 'media' },
    { id: 'q2_13', text: "Chi è l'autore del romanzo 'Il nome della rosa'?", options: ["Italo Calvino", "Umberto Eco", "Primo Levi", "Cesare Pavese"], correctAnswer: 1, difficulty: 'media' },
    { id: 'q2_14', text: "Quale di questi film è stato diretto da Federico Fellini?", options: ["Ladri di biciclette", "La dolce vita", "Rocco e i suoi fratelli", "L'eclisse"], correctAnswer: 1, difficulty: 'media' },
    { id: 'q2_15', text: "Chi ha scolpito il 'David'?", options: ["Donatello", "Bernini", "Michelangelo", "Canova"], correctAnswer: 2, difficulty: 'facile' },
    { id: 'q2_16', text: "Qual è il genere musicale di Miles Davis?", options: ["Rock", "Blues", "Jazz", "Pop"], correctAnswer: 2, difficulty: 'facile' },
    { id: 'q2_17', text: "Chi ha scritto 'Orgoglio e pregiudizio'?", options: ["Charlotte Bronte", "Emily Bronte", "Jane Austen", "Virginia Woolf"], correctAnswer: 2, difficulty: 'media' },
    { id: 'q2_18', text: "Quale di questi attori ha vinto l'Oscar per 'The Revenant'?", options: ["Brad Pitt", "Johnny Depp", "Leonardo DiCaprio", "Tom Hardy"], correctAnswer: 2, difficulty: 'facile' },
    { id: 'q2_19', text: "Chi è il protagonista del film 'Forrest Gump'?", options: ["Tom Cruise", "Tom Hanks", "Brad Pitt", "Keanu Reeves"], correctAnswer: 1, difficulty: 'facile' },
    { id: 'q2_20', text: "Quale opera lirica contiene l'aria 'Nessun dorma'?", options: ["Aida", "Tosca", "Turandot", "La Traviata"], correctAnswer: 2, difficulty: 'difficile' }
  ],
  QUAL_3: [
    { id: 'q3_1', text: "Qual è la velocità della luce?", options: ["300.000 km/s", "150.000 km/s", "500.000 km/s", "1.000.000 km/s"], correctAnswer: 0, difficulty: 'facile' },
    { id: 'q3_2', text: "Quale nazione ha vinto più Mondiali di calcio?", options: ["Germania", "Italia", "Brasile", "Argentina"], correctAnswer: 2, difficulty: 'facile' },
    { id: 'q3_3', text: "Chi ha inventato la lampadina?", options: ["Nikola Tesla", "Thomas Edison", "Alexander Graham Bell", "Guglielmo Marconi"], correctAnswer: 1, difficulty: 'facile' },
    { id: 'q3_4', text: "Qual è il metallo più prezioso?", options: ["Oro", "Platino", "Rodio", "Palladio"], correctAnswer: 2, difficulty: 'media' },
    { id: 'q3_5', text: "In che anno è iniziata la Prima Guerra Mondiale?", options: ["1912", "1914", "1918", "1939"], correctAnswer: 1, difficulty: 'media' },
    { id: 'q3_6', text: "Qual è l'osso più lungo del corpo umano?", options: ["Omero", "Femore", "Tibia", "Radio"], correctAnswer: 1, difficulty: 'media' },
    { id: 'q3_7', text: "Chi è il fondatore di Microsoft?", options: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Jeff Bezos"], correctAnswer: 1, difficulty: 'difficile' },
    { id: 'q3_8', text: "Qual è la capitale del Giappone?", options: ["Kyoto", "Osaka", "Tokyo", "Hiroshima"], correctAnswer: 2, difficulty: 'difficile' },
    { id: 'q3_9', text: "Quanti denti ha un adulto umano?", options: ["28", "30", "32", "34"], correctAnswer: 2, difficulty: 'difficile' },
    { id: 'q3_10', text: "Qual è l'oceano più profondo?", options: ["Atlantico", "Indiano", "Pacifico", "Artico"], correctAnswer: 2, difficulty: 'difficile' },
    { id: 'q3_11', text: "Qual è la formula chimica dell'acqua?", options: ["CO2", "H2O", "NaCl", "O2"], correctAnswer: 1, difficulty: 'facile' },
    { id: 'q3_12', text: "Chi è l'uomo più ricco del mondo (2024)?", options: ["Bill Gates", "Elon Musk", "Jeff Bezos", "Bernard Arnault"], correctAnswer: 1, difficulty: 'media' },
    { id: 'q3_13', text: "In quale continente si trova il deserto del Sahara?", options: ["Asia", "Africa", "America", "Australia"], correctAnswer: 1, difficulty: 'facile' },
    { id: 'q3_14', text: "Qual è il simbolo chimico dell'oro?", options: ["Ag", "Au", "Fe", "Pb"], correctAnswer: 1, difficulty: 'facile' },
    { id: 'q3_15', text: "Chi ha dipinto la Cappella Sistina?", options: ["Leonardo", "Raffaello", "Michelangelo", "Donatello"], correctAnswer: 2, difficulty: 'media' },
    { id: 'q3_16', text: "Qual è la montagna più alta del mondo?", options: ["K2", "Everest", "Monte Bianco", "Kilimangiaro"], correctAnswer: 1, difficulty: 'facile' },
    { id: 'q3_17', text: "Qual è l'organo più grande del corpo umano?", options: ["Cuore", "Cervello", "Fegato", "Pelle"], correctAnswer: 3, difficulty: 'media' },
    { id: 'q3_18', text: "Chi ha scritto 'Il Piccolo Principe'?", options: ["Saint-Exupéry", "Victor Hugo", "Jules Verne", "Albert Camus"], correctAnswer: 0, difficulty: 'media' },
    { id: 'q3_19', text: "Qual è la capitale della Spagna?", options: ["Barcellona", "Siviglia", "Madrid", "Valencia"], correctAnswer: 2, difficulty: 'facile' },
    { id: 'q3_20', text: "Quanti minuti ci sono in un giorno?", options: ["1200", "1440", "1500", "1600"], correctAnswer: 1, difficulty: 'difficile' }
  ],
  SEMIS: [
    { id: 's1', text: "Qual è il nome della particella subatomica con carica negativa?", difficulty: 'facile' },
    { id: 's2', text: "In quale anno l'uomo è sbarcato sulla Luna per la prima volta?", difficulty: 'media' },
    { id: 's3', text: "Chi è l'autore del dipinto 'L'urlo'?", difficulty: 'difficile' },
    { id: 's4', text: "Qual è la capitale del Canada?", difficulty: 'media' },
    { id: 's5', text: "Quale gas costituisce circa il 78% dell'atmosfera terrestre?", difficulty: 'difficile' },
    { id: 's6', text: "Chi ha formulato la teoria della relatività?", difficulty: 'media' },
    { id: 's7', text: "Qual è il deserto più grande del mondo?", difficulty: 'difficile' },
    { id: 's8', text: "Chi è stato il primo presidente degli Stati Uniti?", difficulty: 'facile' },
    { id: 's9', text: "Qual è la capitale della Russia?", difficulty: 'facile' },
    { id: 's10', text: "Chi ha scritto 'I promessi sposi'?", difficulty: 'facile' }
  ],
  FINAL: [
    { id: 'f1', text: "Qual è il numero atomico dell'oro?", difficulty: 'difficile' },
    { id: 'f2', text: "Chi scrisse 'Il Milione'?", difficulty: 'media' },
    { id: 'f3', text: "Qual è la montagna più alta d'Europa (considerando il Caucaso)?", difficulty: 'difficile' },
    { id: 'f4', text: "In che anno è stata fondata l'ONU?", difficulty: 'media' },
    { id: 'f5', text: "Qual è il nome del primo satellite artificiale lanciato in orbita?", difficulty: 'difficile' },
    { id: 'f6', text: "Qual è l'opera più famosa di Dante Alighieri?", difficulty: 'facile' },
    { id: 'f7', text: "Chi ha scoperto la penicillina?", difficulty: 'difficile' },
    { id: 'f8', text: "Qual è la capitale dell'Islanda?", difficulty: 'media' },
    { id: 'f9', text: "In che anno è scoppiata la Rivoluzione Francese?", difficulty: 'media' },
    { id: 'f10', text: "Chi ha dipinto 'Guernica'?", difficulty: 'difficile' }
  ]
};
